# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f62f238bc69a52c899229c24f2f68320b1cd38bb0fd8728c0ecc41b90af7567ba67028234ee2fbe147cd20334cfe73f91ce2ceb80d89e5e738b18cbad8ed41e

test:
  secret_key_base: 4a6d5ee5a1711ab078956f862dbf1746454ba8f36f532aeda26044d779c439080446c509bb6d8f63be80cc321913afffbe92c238e90ae9321ee163cf2c87eeb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
